document.addEventListener("DOMContentLoaded", () => {
  const calculateCompatibility = (event) => {
    event.preventDefault();

    const sign1 = document.getElementById("sign1").value.toLowerCase();
    const sign2 = document.getElementById("sign2").value.toLowerCase();
    const aspect = document.getElementById("aspect").value.toLowerCase();

    if (!sign1 || !sign2 || !aspect) {
      alert("Please select both signs and an aspect.");
      return;
    }

    let compatibilityMessage = getCompatibilityMessage(sign1, sign2, aspect);

    // Display the result
    const resultContainer = document.getElementById("result");
    resultContainer.textContent = compatibilityMessage;
  };

  const getCompatibilityMessage = (sign1, sign2, aspect) => {
    const compatibilities = {
      love: {
        aries: {
          taurus: "Moderate",
          gemini: "High",
          cancer: "Low",
          leo: "High",
          virgo: "Moderate",
          libra: "High",
          scorpio: "Low",
          sagittarius: "High",
          capricorn: "Moderate",
          aquarius: "High",
          pisces: "Low",
          aries: "Moderate",
        },
        taurus: {
          aries: "Moderate",
          gemini: "Moderate",
          cancer: "High",
          leo: "Moderate",
          virgo: "High",
          libra: "Moderate",
          scorpio: "High",
          sagittarius: "Low",
          capricorn: "High",
          aquarius: "Low",
          pisces: "High",
          taurus: "Moderate",
        },
        gemini: {
          aries: "High",
          taurus: "Moderate",
          cancer: "Low",
          leo: "High",
          virgo: "Moderate",
          libra: "High",
          scorpio: "Low",
          sagittarius: "High",
          capricorn: "Moderate",
          aquarius: "High",
          pisces: "Low",
          gemini: "Moderate",
        },
        cancer: {
          aries: "Low",
          taurus: "High",
          gemini: "Low",
          leo: "Moderate",
          virgo: "High",
          libra: "Low",
          scorpio: "High",
          sagittarius: "Low",
          capricorn: "Moderate",
          aquarius: "Low",
          pisces: "High",
          cancer: "Moderate",
        },
        leo: {
          aries: "High",
          taurus: "Moderate",
          gemini: "High",
          cancer: "Moderate",
          virgo: "Moderate",
          libra: "High",
          scorpio: "Low",
          sagittarius: "High",
          capricorn: "Moderate",
          aquarius: "High",
          pisces: "Low",
          leo: "Moderate",
        },
        virgo: {
          aries: "Moderate",
          taurus: "High",
          gemini: "Moderate",
          cancer: "High",
          leo: "Moderate",
          libra: "Moderate",
          scorpio: "Moderate",
          sagittarius: "Low",
          capricorn: "High",
          aquarius: "Moderate",
          pisces: "High",
          virgo: "Moderate",
        },
        libra: {
          aries: "High",
          taurus: "Moderate",
          gemini: "High",
          cancer: "Low",
          leo: "High",
          virgo: "Moderate",
          scorpio: "Low",
          sagittarius: "High",
          capricorn: "Moderate",
          aquarius: "High",
          pisces: "Low",
          libra: "Moderate",
        },
        scorpio: {
          aries: "Low",
          taurus: "High",
          gemini: "Low",
          cancer: "High",
          leo: "Low",
          virgo: "Moderate",
          libra: "Low",
          sagittarius: "Low",
          capricorn: "High",
          aquarius: "Low",
          pisces: "High",
          scorpio: "Moderate",
        },
        sagittarius: {
          aries: "High",
          taurus: "Low",
          gemini: "High",
          cancer: "Low",
          leo: "High",
          virgo: "Low",
          libra: "High",
          scorpio: "Low",
          capricorn: "Moderate",
          aquarius: "High",
          pisces: "Low",
          sagittarius: "Moderate",
        },
        capricorn: {
          aries: "Moderate",
          taurus: "High",
          gemini: "Moderate",
          cancer: "Low",
          leo: "Moderate",
          virgo: "High",
          libra: "Moderate",
          scorpio: "High",
          sagittarius: "Moderate",
          capricorn: "Moderate",
          aquarius: "Low",
          pisces: "High",
        },
        aquarius: {
          aries: "High",
          taurus: "Low",
          gemini: "High",
          cancer: "Low",
          leo: "High",
          virgo: "Moderate",
          libra: "High",
          scorpio: "Low",
          sagittarius: "High",
          capricorn: "Low",
          pisces: "Moderate",
          aquarius: "Moderate",
        },
        pisces: {
          aries: "Low",
          taurus: "High",
          gemini: "Low",
          cancer: "High",
          leo: "Low",
          virgo: "High",
          libra: "Low",
          scorpio: "High",
          sagittarius: "Low",
          capricorn: "High",
          aquarius: "Moderate",
          pisces: "Moderate",
        },
      },
      friendship: {
        aries: {
          taurus: "High",
          gemini: "High",
          cancer: "Moderate",
          leo: "High",
          virgo: "Moderate",
          libra: "High",
          scorpio: "Low",
          sagittarius: "High",
          capricorn: "Moderate",
          aquarius: "High",
          pisces: "Low",
          aries: "High",
        },
        taurus: {
          aries: "High",
          gemini: "Moderate",
          cancer: "High",
          leo: "Moderate",
          virgo: "High",
          libra: "Moderate",
          scorpio: "Moderate",
          sagittarius: "Low",
          capricorn: "High",
          aquarius: "Low",
          pisces: "High",
          taurus: "High",
        },
        gemini: {
          aries: "High",
          taurus: "Moderate",
          cancer: "Moderate",
          leo: "High",
          virgo: "Moderate",
          libra: "High",
          scorpio: "Low",
          sagittarius: "High",
          capricorn: "Moderate",
          aquarius: "High",
          pisces: "Low",
          gemini: "High",
        },
        cancer: {
          aries: "Moderate",
          taurus: "High",
          gemini: "Moderate",
          leo: "Low",
          virgo: "Moderate",
          libra: "Low",
          scorpio: "High",
          sagittarius: "Low",
          capricorn: "Moderate",
          aquarius: "Low",
          pisces: "High",
          cancer: "Moderate",
        },
        leo: {
          aries: "High",
          taurus: "Moderate",
          gemini: "High",
          cancer: "Low",
          virgo: "Moderate",
          libra: "High",
          scorpio: "Low",
          sagittarius: "High",
          capricorn: "Moderate",
          aquarius: "High",
          pisces: "Low",
          leo: "High",
        },
        virgo: {
          aries: "Moderate",
          taurus: "High",
          gemini: "Moderate",
          cancer: "Moderate",
          leo: "Moderate",
          libra: "Moderate",
          scorpio: "Low",
          sagittarius: "Low",
          capricorn: "High",
          aquarius: "Moderate",
          pisces: "Moderate",
          virgo: "Moderate",
        },
        libra: {
          aries: "High",
          taurus: "Moderate",
          gemini: "High",
          cancer: "Low",
          leo: "High",
          virgo: "Moderate",
          scorpio: "Low",
          sagittarius: "High",
          capricorn: "Moderate",
          aquarius: "High",
          pisces: "Low",
          libra: "High",
        },
        scorpio: {
          aries: "Low",
          taurus: "Moderate",
          gemini: "Low",
          cancer: "High",
          leo: "Low",
          virgo: "Low",
          libra: "Low",
          sagittarius: "Low",
          capricorn: "High",
          aquarius: "Low",
          pisces: "High",
          scorpio: "Moderate",
        },
        sagittarius: {
          aries: "High",
          taurus: "Low",
          gemini: "High",
          cancer: "Low",
          leo: "High",
          virgo: "Low",
          libra: "High",
          scorpio: "Low",
          capricorn: "Moderate",
          aquarius: "High",
          pisces: "Low",
          sagittarius: "Moderate",
        },
        capricorn: {
          aries: "Moderate",
          taurus: "High",
          gemini: "Moderate",
          cancer: "Low",
          leo: "Moderate",
          virgo: "High",
          libra: "Moderate",
          scorpio: "High",
          sagittarius: "Moderate",
          capricorn: "Moderate",
          aquarius: "Low",
          pisces: "High",
        },
        aquarius: {
          aries: "High",
          taurus: "Low",
          gemini: "High",
          cancer: "Low",
          leo: "High",
          virgo: "Moderate",
          libra: "High",
          scorpio: "Low",
          sagittarius: "High",
          capricorn: "Low",
          pisces: "Moderate",
          aquarius: "Moderate",
        },
        pisces: {
          aries: "Low",
          taurus: "High",
          gemini: "Low",
          cancer: "High",
          leo: "Low",
          virgo: "High",
          libra: "Low",
          scorpio: "High",
          sagittarius: "Low",
          capricorn: "High",
          aquarius: "Moderate",
          pisces: "Moderate",
        },
      },
      work: {
        aries: {
          taurus: "Moderate",
          gemini: "High",
          cancer: "Moderate",
          leo: "High",
          virgo: "High",
          libra: "Moderate",
          scorpio: "Moderate",
          sagittarius: "High",
          capricorn: "High",
          aquarius: "High",
          pisces: "Moderate",
          aries: "High",
        },
        taurus: {
          aries: "Moderate",
          gemini: "High",
          cancer: "High",
          leo: "Moderate",
          virgo: "High",
          libra: "Moderate",
          scorpio: "Moderate",
          sagittarius: "Moderate",
          capricorn: "High",
          aquarius: "Moderate",
          pisces: "Moderate",
          taurus: "High",
        },
        gemini: {
          aries: "High",
          taurus: "High",
          cancer: "Moderate",
          leo: "High",
          virgo: "Moderate",
          libra: "High",
          scorpio: "Moderate",
          sagittarius: "High",
          capricorn: "High",
          aquarius: "High",
          pisces: "Moderate",
          gemini: "High",
        },
        cancer: {
          aries: "Moderate",
          taurus: "High",
          gemini: "Moderate",
          leo: "Low",
          virgo: "High",
          libra: "Moderate",
          scorpio: "High",
          sagittarius: "Low",
          capricorn: "Moderate",
          aquarius: "Low",
          pisces: "High",
          cancer: "Moderate",
        },
        leo: {
          aries: "High",
          taurus: "Moderate",
          gemini: "High",
          cancer: "Low",
          virgo: "Moderate",
          libra: "High",
          scorpio: "Low",
          sagittarius: "High",
          capricorn: "Moderate",
          aquarius: "High",
          pisces: "Low",
          leo: "High",
        },
        virgo: {
          aries: "High",
          taurus: "High",
          gemini: "Moderate",
          cancer: "High",
          leo: "Moderate",
          libra: "Moderate",
          scorpio: "Moderate",
          sagittarius: "Low",
          capricorn: "High",
          aquarius: "Moderate",
          pisces: "High",
          virgo: "High",
        },
        libra: {
          aries: "Moderate",
          taurus: "Moderate",
          gemini: "High",
          cancer: "Low",
          leo: "High",
          virgo: "Moderate",
          scorpio: "Low",
          sagittarius: "High",
          capricorn: "Moderate",
          aquarius: "High",
          pisces: "Low",
          libra: "High",
        },
        scorpio: {
          aries: "Moderate",
          taurus: "Moderate",
          gemini: "Moderate",
          cancer: "High",
          leo: "Low",
          virgo: "Moderate",
          libra: "Low",
          sagittarius: "Low",
          capricorn: "High",
          aquarius: "Moderate",
          pisces: "High",
          scorpio: "Moderate",
        },
        sagittarius: {
          aries: "High",
          taurus: "Moderate",
          gemini: "High",
          cancer: "Low",
          leo: "High",
          virgo: "Low",
          libra: "High",
          scorpio: "Low",
          capricorn: "Moderate",
          aquarius: "High",
          pisces: "Low",
          sagittarius: "Moderate",
        },
        capricorn: {
          aries: "High",
          taurus: "High",
          gemini: "High",
          cancer: "Moderate",
          leo: "Moderate",
          virgo: "High",
          libra: "Moderate",
          scorpio: "High",
          sagittarius: "Moderate",
          capricorn: "Moderate",
          aquarius: "Low",
          pisces: "High",
        },
        aquarius: {
          aries: "High",
          taurus: "Moderate",
          gemini: "High",
          cancer: "Low",
          leo: "High",
          virgo: "Moderate",
          libra: "High",
          scorpio: "Moderate",
          sagittarius: "High",
          capricorn: "Low",
          pisces: "Moderate",
          aquarius: "Moderate",
        },
        pisces: {
          aries: "Moderate",
          taurus: "Moderate",
          gemini: "Moderate",
          cancer: "High",
          leo: "Low",
          virgo: "High",
          libra: "Low",
          scorpio: "High",
          sagittarius: "Low",
          capricorn: "High",
          aquarius: "Moderate",
          pisces: "Moderate",
        },
      },
    };

    const aspectCompatibilities = compatibilities[aspect];
    if (aspectCompatibilities) {
      const sign1Compatibilities = aspectCompatibilities[sign1];
      if (sign1Compatibilities) {
        const compatibility = sign1Compatibilities[sign2];
        if (compatibility) {
          return `The ${aspect} compatibility between ${capitalize(
            sign1
          )} and ${capitalize(sign2)} is ${compatibility}.`;
        }
      }
    }
    return `Compatibility between ${capitalize(sign1)} and ${capitalize(
      sign2
    )} is unknown.`;
  };

  const capitalize = (word) => {
    return word.charAt(0).toUpperCase() + word.slice(1);
  };

  document
    .querySelector(".button")
    .addEventListener("click", calculateCompatibility);
});
